using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MongoDB.Driver;
using MongoDB.Driver.Linq;
using System.Linq.Expressions;

namespace PairMatching.DataAccess.Infrastructure
{
    public class MongoDataAccess : IDataAccess
    {
        // The connections strings of the database
        readonly string _connctionsStrings;

        readonly string _databaseName;

        public MongoDataAccess(string connctionsStrings, string databaseName)
        {
            _connctionsStrings = connctionsStrings;
            _databaseName = databaseName;
        }

        public MongoDataAccess(string connctionsStrings) : this(connctionsStrings, "Shalhevet")
        {
        }

        private IMongoCollection<T> ConnectToMongo<T>(string collectionName)
        {
            var client = new MongoClient(_connctionsStrings);

            var db = client.GetDatabase(_databaseName);

            return db.GetCollection<T>(collectionName);
        }

        public async Task<T> LoadOneAsync<T>(string collectionName, int id)
        {
            try
            {
                var collection = ConnectToMongo<T>(collectionName);

                var filter = Builders<T>.Filter.Eq("Id", id);

                var record = await collection.FindAsync(filter)
                    .ConfigureAwait(false);
                
                return await record.FirstOrDefaultAsync()
                    .ConfigureAwait(false);
            }       
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<T> LoadOneAsync<T>(string collectionName, string id)
        {
            try
            {
                var collection = ConnectToMongo<T>(collectionName);

                var filter = Builders<T>.Filter.Eq("Id", id);

                var record = await collection.FindAsync(filter)
                    .ConfigureAwait(false);

                return await record.FirstOrDefaultAsync()
                    .ConfigureAwait(false);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public async Task<IEnumerable<T>> LoadManyAsync<T>(string collectionName, Expression<Func<T, bool>> predicate = null)
        {
            var collection = ConnectToMongo<T>(collectionName);

            IAsyncCursor<T> records;

            if (predicate != null)
            {
                var filter = Builders<T>.Filter.Where(predicate);
                records = await collection.FindAsync(filter)
                    .ConfigureAwait(false);
            }
            else
            {
                records = await collection.FindAsync(_ => true)
                    .ConfigureAwait(false);
            }

            return await records.ToListAsync()
                .ConfigureAwait(false);
        }

        public Task InsertMany<T>(string collectionName, IEnumerable<T> records)
        {
            var collection = ConnectToMongo<T>(collectionName);

            return collection.InsertManyAsync(records);
        }

        /// <summary>
        /// Insert a single record to the database
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="collectionName">The collcetion name in mongo</param>
        /// <param name="record"></param>
        /// <returns>The same record with a new id</returns>
        public async Task<T> InsertOne<T>(string collectionName, T record)
        {
            var collection = ConnectToMongo<T>(collectionName);

            await collection.InsertOneAsync(record)
                .ConfigureAwait(false);
            // the record now has an id generated by mongo
            return record;
        }

        /// <summary>
        /// Update a single record in the database
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="collectionName">The collcetion name in mongo</param>
        /// <param name="record">The record</param>
        /// <param name="id">The id of the record. Can be int or string</param>
        /// <returns>The task of the action</returns>
        public Task UpdateOne<T>(string collectionName, T record, dynamic id)
        {
            var collection = ConnectToMongo<T>(collectionName);

            var filter = Builders<T>.Filter.Eq("Id", id);

            return collection.ReplaceOneAsync(filter, record, 
                        new ReplaceOptions { IsUpsert = true });
        }

        public Task Delete<T>(string collectionName, dynamic id)
        {
            var collection = ConnectToMongo<T>(collectionName);

            var filter = Builders<T>.Filter.Eq("Id", id);

            return collection.DeleteOneAsync(filter);
        }
    }
}
